CREATE TABLE IF NOT EXISTS [dt_user] (
	[id] INT IDENTITY PRIMARY KEY,
	[username] VARCHAR(64) UNIQUE NOT NULL,
	[password] VARCHAR(256) UNIQUE NOT NULL,
	[address] VARCHAR(128) UNIQUE NOT NULL,
	[active] BIT DEFAULT(0),
	[session] VARCHAR(64) UNIQUE DEFAULT('')
)
